title: Large Agent Collider
subtitle: Univeristy of Oxford
description: Research group focused on the advancement of design, verification, and calibration of agent-based models.
header: images/background.jpg
footer: images/background.jpg
links:
  email: arnau.quera-bofarull@cs.ox.ac.uk
    #orcid: 0000-0001-5055-9863
    #google-scholar: 8VGz9BIAAAAJ
  github: largeagentcollider
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: arnau.quera-bofarull@cs.ox.ac.uk
github: LargeAgentCollider
  #twitter: LargeAgentCollider
  #instagram: LargeAgentCollider
  #youtube: LargeAgentCollider
